config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount API => '/'

  root to: 'attachments#index'

  resources :users, only: [:new, :create]

  # sessions routes
  get '/login',     to: 'sessions#new', as: 'login'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  resources :attachments, only: %i[new create]
end

app/models/api_key.rb
# frozen_string_literal: true

class APIKey < ApplicationRecord
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
# frozen_string_literal: true

class Attachment < ApplicationRecord
  has_one_attached :file

  belongs_to :user

  def file_url
    Rails.application.routes.url_helpers.polymorphic_url(file, host: ENV.fetch('HOST_NAME', 'example.com'))
  end
end

app/models/authentication_token.rb
# frozen_string_literal: true

class AuthenticationToken < ApplicationRecord
  belongs_to :user

  validates :token, presence: true
  scope :valid, -> { where(expires_at: nil).or(where('expires_at > ?', Time.current)) }

  class << self
    def generate(user)
      create(token: SecureRandom.hex, user: user)
    end
  end
end

app/models/error_codes.rb
# frozen_string_literal: true

module ErrorCodes
  DEVELOPER_KEY_MISSING = 1001
  BAD_AUTHENTICATION_PARAMS = 401
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  has_many :attachments
  has_many :authentication_tokens

  validates :email, presence: true,
                    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: 'format invalid' },
                    uniqueness: { case_sensitive: false },
                    length: { minimum: 4, maximum: 254 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend

  helper_method :current_user

  before_action :require_login

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def require_login
    redirect_to login_path unless session.include? :user_id
  end
end

app/controllers/attachments_controller.rb
# frozen_string_literal: true

class AttachmentsController < ApplicationController
  def new
    @attachment = Attachment.new
  end

  def create
    @file_zipper_service = FilesZipperService.new(create_params[:files], current_user)
    @attachment = @file_zipper_service.call

    if @attachment.save
      password_notice
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @pagy, @attachments = pagy(Attachment.all.where(user: current_user).order(created_at: :desc))
  end

  private

  def create_params
    params.require(:attachment).permit(files: [])
  end

  def password_notice
    flash[:success] = "Hasło do twojego pliku: #{@file_zipper_service&.secure_random}"
  end

  rescue_from ActionController::ParameterMissing do
    flash.now[:danger] = 'Dodaj co najmniej jeden plik'
    @attachment = Attachment.new
    render :new
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    user = User.find_by(email: session_params[:email])
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to :root
    else
      flash.now[:danger] = 'Nieprawidłowy email lub hasło'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Zostałeś wylogowany'
    redirect_to login_path
  end

  private

  def session_params
    params.require(:login).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to :login
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/views/attachments/index.html.haml
!= pagy_bootstrap_nav(@pagy)
%table.table
  %thead
    %tr
      %th Data utworzenia
      %th Nazwa pliku
      %th Rozmiar
      %th Link
  %tbody
    - @attachments.each do |attachment|
      %tr
        %td= attachment.created_at.to_date
        %td= attachment.file.filename
        %td= number_to_human_size(attachment.file.byte_size)
        %td= link_to 'Pobierz', attachment.file

app/views/attachments/new.html.haml
= simple_form_for @attachment do |f|
  = f.input :file, input_html: { multiple: "true", name: "attachment[files][]" },
    label: "Dodaj pliki",
    hint: "Pliki zostaną skompresowane do jednego archiwum w formacie zip"
  = f.button :submit, "Stwórz archiwum", class: "btn-primary"

app/views/layouts/_header.html.haml
%header.d-flex.flex-wrap.justify-content-center.py-3.mb-4.border-bottom
  = link_to root_path, class: "d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none" do
    %span.fs-4 Zipper
  %ul.nav.nav-pills
    - if current_user
      %li.nav-item= link_to 'Lista plików', root_path, class: ['nav-link', ('active' if current_page?(root_path))]
      %li.nav-item= link_to 'Dodaj plik', new_attachment_path, class: ['nav-link', ('active' if current_page?(new_attachment_path))]
      %li.nav-item= link_to 'Wyloguj się', logout_path, method: :delete, class: 'nav-link'
    - else
      %li.nav-item= link_to 'Zaloguj się', login_path, class: 'btn btn-primary'
      %li.nav-item= link_to 'Utwórz konto', new_user_path, class: 'nav-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Zipper
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body

    %main
      .container
        = render 'layouts/header'
        - flash.each do |type, msg|
          %div{ class: "alert alert-#{type} alert-dismissible fade show", role: "alert" }
            = msg
            %button{ type: "button", class: "btn-close", "data-bs-dismiss": "alert", "aria-label": "Close" }
        = yield

app/views/users/create.html.haml
%h1 Users#create
%p Find me in app/views/users/create.html.haml

app/views/users/new.html.haml
%h1 Rejestracja
= simple_form_for @user do |f|
  = f.input :email, label: "Email", required: true
  = f.input :password, label: "Hasło", required: true
  = f.input :password_confirmation, label: "Potwierdź hasło", required: true
  = f.button :submit, "Załóż konto", class: "btn-primary"